
package org.example.soap.server;

import javax.activation.DataHandler;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "FileReceiverService", targetNamespace = "http://server.soap.example.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface FileReceiverService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "uploadFile", targetNamespace = "http://server.soap.example.org/", className = "org.example.soap.server.UploadFile")
    @ResponseWrapper(localName = "uploadFileResponse", targetNamespace = "http://server.soap.example.org/", className = "org.example.soap.server.UploadFileResponse")
    public String uploadFile(
        @WebParam(name = "arg0", targetNamespace = "")
        DataHandler arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
