
package org.example.soap.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "FileReceiverServiceService", targetNamespace = "http://server.soap.example.org/", wsdlLocation = "file:/home/nagetsum/jboss/eap7/7.3.5/jboss-eap-7.3/standalone/data/wsdl/mtom-server.war/FileReceiverServiceService.wsdl")
public class FileReceiverServiceService
    extends Service
{

    private final static URL FILERECEIVERSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException FILERECEIVERSERVICESERVICE_EXCEPTION;
    private final static QName FILERECEIVERSERVICESERVICE_QNAME = new QName("http://server.soap.example.org/", "FileReceiverServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/nagetsum/jboss/eap7/7.3.5/jboss-eap-7.3/standalone/data/wsdl/mtom-server.war/FileReceiverServiceService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        FILERECEIVERSERVICESERVICE_WSDL_LOCATION = url;
        FILERECEIVERSERVICESERVICE_EXCEPTION = e;
    }

    public FileReceiverServiceService() {
        super(__getWsdlLocation(), FILERECEIVERSERVICESERVICE_QNAME);
    }

    public FileReceiverServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), FILERECEIVERSERVICESERVICE_QNAME, features);
    }

    public FileReceiverServiceService(URL wsdlLocation) {
        super(wsdlLocation, FILERECEIVERSERVICESERVICE_QNAME);
    }

    public FileReceiverServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, FILERECEIVERSERVICESERVICE_QNAME, features);
    }

    public FileReceiverServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public FileReceiverServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns FileReceiverService
     */
    @WebEndpoint(name = "FileReceiverServicePort")
    public FileReceiverService getFileReceiverServicePort() {
        return super.getPort(new QName("http://server.soap.example.org/", "FileReceiverServicePort"), FileReceiverService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns FileReceiverService
     */
    @WebEndpoint(name = "FileReceiverServicePort")
    public FileReceiverService getFileReceiverServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.soap.example.org/", "FileReceiverServicePort"), FileReceiverService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (FILERECEIVERSERVICESERVICE_EXCEPTION!= null) {
            throw FILERECEIVERSERVICESERVICE_EXCEPTION;
        }
        return FILERECEIVERSERVICESERVICE_WSDL_LOCATION;
    }

}
