package org.jboss.ws.hello;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 2.7.14.redhat-1
 * 2021-09-11T22:04:23.386+09:00
 * Generated source version: 2.7.14.redhat-1
 * 
 */
@WebService(targetNamespace = "http://hello.ws.jboss.org/", name = "Hello")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface Hello {

    @WebMethod
    @WebResult(name = "result", targetNamespace = "http://hello.ws.jboss.org/", partName = "result")
    public java.lang.String hello(
        @WebParam(partName = "String_1", name = "String_1")
        java.lang.String string1
    );
}
