package org.jboss.jbossws.ws_extensions.wssecuritypolicy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.5.8.redhat-00001
 * 2024-12-17T17:14:54.904+09:00
 * Generated source version: 3.5.8.redhat-00001
 *
 */
@WebServiceClient(name = "SecurityService",
                  wsdlLocation = "http://localhost:8080/ws-security-server/SecurityService?wsdl",
                  targetNamespace = "http://www.jboss.org/jbossws/ws-extensions/wssecuritypolicy")
public class SecurityService extends Service {

    public static final URL WSDL_LOCATION;

    public static final QName SERVICE = new QName("http://www.jboss.org/jbossws/ws-extensions/wssecuritypolicy", "SecurityService");
    public static final QName SecurityServicePort = new QName("http://www.jboss.org/jbossws/ws-extensions/wssecuritypolicy", "SecurityServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/ws-security-server/SecurityService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SecurityService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/ws-security-server/SecurityService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SecurityService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SecurityService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SecurityService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public SecurityService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SecurityService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SecurityService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ServiceIface
     */
    @WebEndpoint(name = "SecurityServicePort")
    public ServiceIface getSecurityServicePort() {
        return super.getPort(SecurityServicePort, ServiceIface.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ServiceIface
     */
    @WebEndpoint(name = "SecurityServicePort")
    public ServiceIface getSecurityServicePort(WebServiceFeature... features) {
        return super.getPort(SecurityServicePort, ServiceIface.class, features);
    }

}
