package org.jboss.jbossws.ws_extensions.wssecuritypolicy;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.5.8.redhat-00001
 * 2024-12-17T17:14:54.869+09:00
 * Generated source version: 3.5.8.redhat-00001
 *
 */
@WebService(targetNamespace = "http://www.jboss.org/jbossws/ws-extensions/wssecuritypolicy", name = "ServiceIface")
@XmlSeeAlso({ObjectFactory.class})
public interface ServiceIface {

    @WebMethod
    @RequestWrapper(localName = "sayHello", targetNamespace = "http://www.jboss.org/jbossws/ws-extensions/wssecuritypolicy", className = "org.jboss.jbossws.ws_extensions.wssecuritypolicy.SayHello")
    @ResponseWrapper(localName = "sayHelloResponse", targetNamespace = "http://www.jboss.org/jbossws/ws-extensions/wssecuritypolicy", className = "org.jboss.jbossws.ws_extensions.wssecuritypolicy.SayHelloResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String sayHello()
;
}
