package org.example.soap.client;

import org.example.soap.server.*;

import javax.activation.DataHandler;
import javax.activation.FileDataSource;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBElement;
import javax.xml.namespace.QName;
import javax.xml.ws.Dispatch;
import javax.xml.ws.Service;
import javax.xml.ws.soap.SOAPBinding;
import java.io.IOException;
import java.io.PrintWriter;
import java.net.URL;

@WebServlet("/client")
public class SoapClientServlet extends HttpServlet {
    private static final String FILEPATH_TO_SEND = "/home/nagetsum/duke.jpg";

    @Override
    public void doGet(HttpServletRequest req, HttpServletResponse res)
            throws IOException {
        res.setContentType("text/plain; charset=utf-8");

        // Option1. using JAX-WS client stub code generated by wsimport command
//        FileReceiverServiceService service = new FileReceiverServiceService();
//        FileReceiverService fileReceiverService = service.getFileReceiverServicePort();
//        SOAPBinding binding = (SOAPBinding) ((BindingProvider) fileReceiverService).getBinding();
//        binding.setMTOMEnabled(true);
//
//        DataHandler dh = new DataHandler(new FileDataSource(FILEPATH_TO_SEND));
//        String result = fileReceiverService.uploadFile(dh, "duke.jpg");
//        res.getWriter().println("result: " + result);

        try {
            // Option2(advanced). using javax.xml.ws.Dispatch interface with Service.Mode.PAYLOAD
            sendRequest(res.getWriter());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void sendRequest(PrintWriter out) throws Exception {
        URL wsdlUrl = new URL("http://127.0.0.1:8080/mtom-server/FileReceiverService?wsdl");
        QName serviceName = new QName("http://server.soap.example.org/", "FileReceiverServiceService");
        QName portName = new QName("http://server.soap.example.org/", "FileReceiverServicePort");

        Service service = Service.create(wsdlUrl, serviceName);
        JAXBContext jbc = JAXBContext.newInstance("org.example.soap.server");
        Dispatch<Object> dispatch = service.createDispatch(portName, jbc, Service.Mode.PAYLOAD);

        // enable MTOM on client side
        SOAPBinding binding = (SOAPBinding) dispatch.getBinding();
        binding.setMTOMEnabled(true);

        UploadFile uploadFile = new UploadFile();
        uploadFile.setArg0(new DataHandler(new FileDataSource(FILEPATH_TO_SEND)));
        uploadFile.setArg1("duke.png");
        ObjectFactory factory = new ObjectFactory();
        JAXBElement<UploadFile> request = factory.createUploadFile(uploadFile);

        JAXBElement<UploadFileResponse> response = (JAXBElement<UploadFileResponse>) dispatch.invoke(request);
        out.println("result:" + response.getValue().getReturn());
    }

      // Option3(advanced). Case Service.Mode.MESSAGE which is the SOAP message with a attachment built by the application.
//    private void sendRequest(PrintWriter out) throws Exception {
//        URL wsdlUrl = new URL("http://127.0.0.1:8080/mtom-server/FileReceiverService?wsdl");
//        QName serviceName = new QName("http://server.soap.example.org/", "FileReceiverServiceService");
//        QName portName = new QName("http://server.soap.example.org/", "FileReceiverServicePort");
//
//        Service service = Service.create(wsdlUrl, serviceName);
//        Dispatch<SOAPMessage> dispatch = service.createDispatch(portName, SOAPMessage.class, Service.Mode.MESSAGE, new MTOMFeature(0));
//        SOAPMessage requestMessage = createMessage();
//        requestMessage.writeTo(System.out);
//        SOAPMessage responseMessage =  dispatch.invoke(requestMessage);
//        out.println("result:" + responseMessage.toString());
//    }
//
      // Continuation of Option 3: the SOAP Body is built by JAXB marchalling.
//    private SOAPMessage createMessage() throws SOAPException, JAXBException, ParserConfigurationException {
//        SOAPMessage soapMessage = MessageFactory.newInstance().createMessage();
//        soapMessage.getSOAPPart().getEnvelope();
//        AttachmentPart attachment = soapMessage.createAttachmentPart(new DataHandler(new FileDataSource(FILEPATH_TO_SEND)));
//        String contentId = "myattachment1";
//        attachment.setContentId(contentId);
//
//        JAXBContext jbc = JAXBContext.newInstance("org.example.soap.server");
//        Marshaller marshaller = jbc.createMarshaller();
//
//        UploadFile uploadFile = new UploadFile();
//        uploadFile.setArg0(new DataHandler(new FileDataSource(FILEPATH_TO_SEND)));
//        uploadFile.setArg1("duke.png");
//        marshaller.marshal(uploadFile, soapMessage.getSOAPBody());
//        return soapMessage;
//    }

//    // Continuation of Option 3 - other option: the SOAP Body is built by javax.xml.soap.* SAAJ(the SOAP with Attachment API for Java) APIs.
//    private SOAPMessage createMessage() throws SOAPException {
//        SOAPMessage soapMessage = MessageFactory.newInstance().createMessage();
//        soapMessage.getSOAPPart().getEnvelope();
//
//        AttachmentPart attachment = soapMessage.createAttachmentPart(new DataHandler(new FileDataSource(FILEPATH_TO_SEND)));
//        String contentId = "myattachment1";
//        attachment.setContentId(contentId);
//
//        SOAPBody soapBody = soapMessage.getSOAPBody();
//        SOAPBodyElement soapBodyRoot = soapBody.addBodyElement(new QName("http://server.soap.example.org/", "uploadFile", "ns"));
//
//        SOAPElement arg0 = soapBodyRoot.addChildElement("arg0");
//        SOAPElement include = arg0.addChildElement(new QName("http://www.w3.org/2004/08/xop/include", "Include","xop"));
//        include.addAttribute(new QName("href"),"cid:" + contentId);
//
//        SOAPElement arg1 = soapBodyRoot.addChildElement("arg1");
//        arg1.addTextNode("duke.png");
//
//        soapMessage.addAttachmentPart(attachment);
//        return soapMessage;
//    }

}
